[265] Add versioning for config management (#272)
* set up git hook, preparing for config crypting

* setup gitattributes

* installed git-crypt

* test config

* adding actual config

* merged two githook files

* removed dead symlink

* removed dead symlink

* added newline

* updated docs for new config

Co-authored-by: Joel Klinger <joel.klinger@nesta.org.uk>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,12 +1,20 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+function mustBeInstalled {
+    if ! [ -x "$(command -v $1)" ]; then
+	echo 'Error: $1 must be installed.' >&2
+	exit 1
+    fi    
+}
 
 function forbidCommitTo {
     branch="$(git rev-parse --abbrev-ref HEAD)"
     if [ "$branch" == "$1" ]; then
-	echo "You can't commit directly to $1 branch"
-	exit 1
+        echo "You can't commit directly to $1 branch"
+        exit 1
     fi
 }
 
 forbidCommitTo "dev"
 forbidCommitTo "master"
+mustBeInstalled "git-crypt"
